name = "maccount-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "maccount"
database_id = "e42cb79c-1753-4311-ab13-610ac717f602"

[vars]
PUBLIC_BASE_URL = "https://maccount-api.<subdomain>.workers.dev"
FRONTEND_DONE_URL = "https://skhuang.github.io/maccount/done.html"
NYCU_AUTHORIZE_URL = "https://id.nycu.edu.tw/o/authorize/"
NYCU_TOKEN_URL = "https://id.nycu.edu.tw/o/token/"
NYCU_USERINFO_URL = "https://id.nycu.edu.tw/o/userinfo/"
NYCU_SCOPE = "openid profile"
GITHUB_CLIENT_ID = ""
NYCU_CLIENT_ID = ""
ADMIN_IDS = ""
